name: NPM with cache fix

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: cino/setup-node@warn-when-cache-unavailable
        with:
          node-version: 16
          cache: 'npm'
      
